### PR TITLE
follow-everybody.bash: rewrite with while-read loop

### PR DESCRIPTION
**Pull request by Foxboron**
Signed-off-by: Morten Linderud <morten@linderud.pw>

### CODE REVIEW

**Comment by diracdeltas** [comment]
@Foxboron sorry this needs a rebase

**Comment by Foxboron** [comment]
Fixed!

**Comment by diracdeltas** [comment]
@Foxboron sorry!! this once again needs a rebase (last one i swear)

**Comment by Foxboron** [comment]
lol, this was suppose to be a quick fix :upside_down_face:

**Pull request closed without merging**
